---
galaxy_info:
  author: Joaquin Menchaca
  description: Apache Storm Role
  company: your company (optional)
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - jessie
  categories:
  - development

dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
