---
# isntall tasks file for storm
- name: Download Storm
  get_url: url='{{ storm_url }}' dest='/tmp/{{ storm_archive }}'
- name: Create Storm Root Directory
  file: path='{{ storm_root }}' state=directory
- name: Stat Storm Home
  stat: path={{ storm_home }}
  register: storm_home_dir
- name: Unarchive Storm
  unarchive: copy=no src='/tmp/{{ storm_archive }}' dest='{{ storm_root }}'
  when: storm_home_dir.stat.exists == False
- name: Stat Storm Archive Dir
  stat: path={{ storm_root }}/{{ storm_name }}
  register: archive_dir
- name: Move Storm Name to Storm Version
  command: creates="{{ storm_home }}" mv {{ storm_root }}/{{ storm_name }} {{ storm_home }}
  when: archive_dir.stat.exists == True
- name: SymLink Storm Binary
  file: src={{ storm_home }}/bin/storm dest=/usr/local/bin/storm state=link

- name: Create Storm Local Directory
  file: path={{ storm_local_dir }} state=directory mode=0755
