#!/usr/bin/env ansible-playbook
# site.yml: site-wide playbook
- include: playbooks/common.yml
#- include: playbooks/zookeeper.yml
- include: playbooks/nimbus.yml
#- include: playbooks/supervisor.yml
