---
# tasks file for common
- template: src=ssh_config.j2 dest=/etc/ssh/ssh_config
- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_ssh_host }} {{item}}" state=present
  with_items:
    - "{{ groups['all'] | difference(inventory_hostname) }}"
